Update embedding.md
567-labs/fastllm pull request #35
Opened 2023-12-27 02:56 UTC by Anmol6

2023-12-27 03:25 UTC, Anmol6 commented
I think it's a really nice use case to introduce people to Modal & embedding inference. I do think that the clarity can probably be improved a bit, especially around the core orchestration decisions. 
eg. 
- clarifying we'll be establishing two separate servers — one inference server & one sevrer that just handles the download job.
- what is an inference server in the context of embeddings?

2023-12-27 04:07 UTC, jxnl commented
cc: @ivanleomk

2023-12-27 21:16 UTC, ivanleomk commented on docs/embedding.md
> +For our embed our function, we'll be using the Hugging Face [Text Embedding Inference](https://github.com/huggingface/text-embeddings-inference) package. We'll walk through how to leverage caching of
Perhaps a rephrase as `For our embedding function` might work better!

2023-12-27 21:17 UTC, ivanleomk commented on docs/embedding.md
> +All the guesswork of managing the life cycle is taken out of the equation for you with Modal by just defining two functions and using a single decorator. Not only so, we can also configure our stub o
Hmm I think the stub object is slightly different from the `stub.cls` object. In this case, we're trying to get the `stub.cls` object to un with different parameters

2023-12-27 21:19 UTC, ivanleomk commented on docs/embedding.md
> +  text_chunks = generate_chunks_from_dataset(subset, chunk_size=512)
Nice catch on the spacing here. Think there's a similar spacing isue for the `dataset=load_from_disk` spacing issue too

2023-12-27 21:23 UTC, ivanleomk commented on docs/embedding.md
> +A Stub is the most basic concept in Modal — it's a description of how to create a Modal application. We can declare it using just 2 lines of code.
This is a nice way to put it and is consistent with the modal docs too for a stub docs - https://modal.com/docs/reference/modal.Stub.

2023-12-27 21:25 UTC, ivanleomk requested changes
left some comments on the suggested changes, just some small changes that I think would be good :)

2023-12-28 00:49 UTC, jxnl commented
@ivanleomk merge whenever you're feeling good

2023-12-29 07:49 UTC, Anmol6 commented
@ivanleomk FF to further edit it too!

2023-12-29 08:29 UTC, ivanleomk approved these changes
Looks good to me @Anmol6, merging in now.

2023-12-29 08:30 UTC, merged